### ISSUE TITLE
Backdrop needed to "blur" out background when side drawer and/or on screen messages are displayed

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#12]
Make a new backdrop component to be used for more than just side drawer

**Comment by wchung42** [comment]
backdrop component is completed. It can be used to darken the page to bring attention to other components.

**Comment by wchung42** [comment]
Can someone test this to see if it interferes with anything?

**Comment by aahmed019** [comment]
Works perfectly fine, all that's needed is an animation so it looks smooth, right now it looks like a magic trick appearing and disappears. Good Job!
