### ISSUE TITLE
Fixing what was fucked up

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#24]
We need to fix the bootstrap stuff and re-align and center all the body elements, navbar, and footer.

**Comment by aahmed019** [comment]
fixed the alignment for navbar and footer to be responsive for all devices. Aligning the body is something that has to be done

**Comment by wchung42** [comment]
I fixed the navbar spacing for now using width: px. It's not a permanent solution tho but I think it works for now

**Comment by aahmed019** [comment]
Overall everything is fixed now.
