### ISSUE TITLE
Creation of home page 

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#4]
Creating a wire frame layout for the home page.

**Comment by ltran0817** [comment]
posted a wireframe to our wiki, need some input please 👍

**Comment by wchung42** [comment]
That looks good. Can you try adding some of the elements that we discussed about for the home page into it such as the layout of the body and footer?

**Comment by ltran0817** [comment]
> That looks good. Can you try adding some of the elements that we discussed about for the home page into it such as the layout of the body and footer?

Ok, i'm on it. It should be ready by tmr.

**Comment by aahmed019** [comment]
In terms of working on the footer, how should I proceed? I placed a temporary one but for the presentation and long term what type of socials will we have as a team?

**Comment by wchung42** [comment]
Github, Facebook, Twitter, Reddit???

**Comment by aahmed019** [comment]
Logo added, I haven't added reddit but I'll add it later if that's what we're going with.
