### ISSUE TITLE
Game doesn't end after all questions are completed

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#45]
We need some sort of ending page for game completion.
Looking forward.
1. Submit and hint buttons should disappear
2. State should change to a "congrats page"
3. Allow user to rate and comment

**Comment by wchung42** [comment]
working on this

**Comment by wchung42** [comment]
Game ends now once the qquestions run out. Still need to get a timer going for the game over condition and testing for it

**Comment by wchung42** [comment]
There is a bug where the last question can receive any input and it will still complete the game

**Comment by ltran0817** [comment]
Have this get fixed yet?

**Comment by wchung42** [comment]
Yes, the bug has been fixed
