### ISSUE TITLE
Reponsive navigation bar

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#5]
The navigation bar should be visible when the user scroll ups at any point on the page

**Comment by wchung42** [comment]
Working on implementing a temp responsive nav bar in react

**Comment by wchung42** [comment]
What are some things that should be in the side drawer? So far I have about us and games list

**Comment by ltran0817** [comment]
Navbar working as intended 👍

**Comment by aahmed019** [comment]
> What are some things that should be in the side drawer? So far I have about us and games list

We'll ultimately move in the log in button there, refer to the wire frame, it's going to be a logo, about page, and finally the sidebar. For now this works.

**Comment by wchung42** [comment]
Thanks
