### ISSUE TITLE
Refining user stories to better suit the goal of the project

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#7]
All members will discuss and refine the user stories

**Comment by aahmed019** [comment]
Making edits to my section

**Comment by wchung42** [comment]
I made edits to my section too. Can someone take a look so we can further refine these user stories?

**Comment by ltran0817** [comment]
As a guest user, you asked for too much, now we will make this website only available to the elites lol.
J/k that looks fine, but you should only be able to play **ONE** game (we gonna have like 2 or 3, what is the point of trying out everything then we have nothing left to serve you 🤔).
You should demand something more details (small features) like "this website looks so ugly, I'd like an option to donate few bucks for the creators to hire some real professionals to fix it.

**Comment by ltran0817** [comment]
> I made edits to my section too. Can someone take a look so we can further refine these user stories?

I like the "10" of your, that's a good way to prevent 80% of cheat unless the players went hardcore to hack coordinate like in Pokemon GO lol. 
You should add: As **a creators /game designer** I **don't** want to **code everything and just create my own game with my imagination and available tools.** so we can work on it as a feature later

**Comment by aahmed019** [comment]
I completed my final review of my submissions for the user stories. I agree with Lam on the addition for the feature listed in the previous comment, it's a good idea to have a template so that game designers/admins can create new games without reinventing the wheel.
