### ISSUE TITLE
Implementation of footer

### ISSUE THREAD

**Issue by wchung42** [aahmed019/CSC473-Project#8]
Design of home page footer

**Comment by aahmed019** [comment]
starting with a temporary template of my own footer

**Comment by wchung42** [comment]
the footer looks good so far

**Comment by aahmed019** [comment]
Updated footer, matches the nav bar more, but the color isn't exact (in case you didn't already notice)

**Comment by wchung42** [comment]
#383838 This is the color I used for the navbar

**Comment by wchung42** [comment]
Footer looks much cleaner. Nice.
